import "@/styles/globals.css";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
} from "@clerk/nextjs";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";
import { Button } from "@/components/ui/button";
import { CloudUpload } from "lucide-react";
import Link from "next/link";
export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html className={`${GeistSans.variable}`}>
        <body className="flex min-h-screen flex-col">
          <header className="flex h-14 items-center px-4 lg:px-6">
            <Link className="flex items-center justify-center" href="#">
              <CloudUpload className="h-6 w-6" />
              <span className="ml-2 text-2xl font-bold">BackflowTested</span>
            </Link>
            <nav className="ml-auto flex items-center gap-4 sm:gap-6">
              <Link
                className="text-sm font-medium underline-offset-4 hover:underline"
                href="#"
              >
                Features
              </Link>
              <Link
                className="text-sm font-medium underline-offset-4 hover:underline"
                href="#"
              >
                Pricing
              </Link>
              <Link
                className="text-sm font-medium underline-offset-4 hover:underline"
                href="#"
              >
                About
              </Link>
              <SignedIn>
                <Button variant="outline" asChild>
                  <Link href="/dashboard">Dashboard</Link>
                </Button>
              </SignedIn>
              <SignedOut>
                <SignInButton mode="modal">
                  <Button variant="outline">Login</Button>
                </SignInButton>
              </SignedOut>
            </nav>
          </header>
          <TRPCReactProvider>{children}</TRPCReactProvider>
          <footer className="flex w-full shrink-0 flex-col items-center gap-2 border-t px-4 py-6 sm:flex-row md:px-6">
            <p className="text-xs text-gray-500 dark:text-gray-400">
              © 2024 BackflowTested. All rights reserved.
            </p>
            <nav className="flex gap-4 sm:ml-auto sm:gap-6">
              <Link
                className="text-xs underline-offset-4 hover:underline"
                href="#"
              >
                Terms of Service
              </Link>
              <Link
                className="text-xs underline-offset-4 hover:underline"
                href="#"
              >
                Privacy
              </Link>
            </nav>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
